In [1]:
#-----------------------------------packages-----------------------------------
import numpy as np
import scipy as sp
import itertools

<b>Theorem 0.1.</b> (Steinitz' Theorem)
Suppose $\mathbf{p} = (p_0,p_1,p_2) \in \mathbb{N}^3$. Then $\mathbf{p} \in \mathbb{F}^3$ <i>if and only if</i> all of the following hold:

- $4 \leq p_0 \leq 2p_2 - 4$
- $4 \leq p_2 \leq 2p_0 - 4$
- $p_0 - p_1 + p_2 = 2$

<b>Corollary</b> (Polytopic Addition in $\mathbb{F}^3$)
$\mathbf{p}, \mathbf{q} \in \mathbb{F}^3 \Rightarrow \mathbf{p} + \mathbf{q} - (4,6,4) \in \mathbb{F}^3$

In [2]:
x = np.array([1,2,3])

In [142]:
#------------------------------steinitz criteria-------------------------------
def steinitz(f_vector):

    return 1 - (((f_vector[0] >= 4)*(f_vector[0] <= 2*f_vector[2] - 4))* 
                ((f_vector[2] >= 4)*(f_vector[2] <= 2*f_vector[0] - 4))*
                (sum([(-1)**n*f_n for n, f_n in enumerate(f_vector)]) == 2))

edge_lim = 50
N_2 = list(itertools.product(*[range(edge_lim + 1)]*2))
N_3 = list(itertools.product(*[range(edge_lim + 1)]*3))

F_3 = [np.array(p) for p in N_3 if steinitz(p) == 0]

In [143]:
cube = np.array([8,12,6])
square_pyramid = np.array([5,8,5])
triangular_prism = np.array([6,9,5])
hexahedron = np.array([5,9,6])

def p_sum(f_vectors, f_weights):

    return (sum(f_vectors*np.array([[n] for n in f_weights])) -
            (sum(f_weights) - 1)*np.array([4, 6, 4]))

In [146]:
#------------------------------polytope subspaces------------------------------
f_vectors = [triangular_prism, square_pyramid, hexahedron]

test_space = {}
for test_vec in F_3:
    for f_weights in N_3:

        if np.all(p_sum(f_vectors, f_weights) == test_vec):
            test_space[str(test_vec)] = f_weights

missing_vecs = [vec for vec in F_3 if str(vec) not in test_space]
len(missing_vecs)/len(F_3)
    

0.0

In [126]:
#------------------------------isomorphism solver------------------------------
test_vec = np.array([20,30,12])
f_vectors = [triangular_prism, square_pyramid, hexahedron]

for f_weights in N_3: # should solve analytically, but lazy...

    if np.all(p_sum(f_vectors, f_weights) == test_vec):
        print(f_weights)

print('solver completed')


(8, 0, 0)
solver completed


There appears to be an endomorphism $\phi: \mathbb{N}^3 \rightarrow \mathbb{F}^3$ given by:

$\phi((\alpha, \beta, \gamma)) =  \alpha(5,9,6) + \beta(5,8,5) + \gamma(6,9,5) + (\alpha+\beta+\gamma-1)(4,6,4)$

and hence,

$\phi((\alpha, \beta, \gamma)) =  (\alpha + \beta + 2\gamma, 3(\alpha + \gamma) + 2\beta, \beta + \gamma + 2\alpha) - (4,6,4)$


Minkowski Addition

In [151]:
np.all(np.array([1,1]) < np.array([2,2]))

True

In [162]:
def mink_add(set_1, set_2):

    new_set = []
    for mem_1 in set_1:
        for mem_2 in set_2:
            new_set.append(mem_1 + mem_2)

    new_set_2 = []
    for test_mem in new_set:
        ext_flag = True
        tmp_set = [i for i in new_set if np.any(i != test_mem)]

        for mem_a in tmp_set:
            for mem_b in tmp_set:

                if np.all((mem_a < test_mem)*(mem_b > test_mem)):
                    ext_flag = False

        if ext_flag == True:

            new_set_2.append(test_mem)



    return new_set_2

square = [np.array([0,0]), np.array([1,0]), np.array([1,1]), np.array([0,1])]

triangle = [np.array([0,0]), np.array([1,0]), np.array([0.5,1])]


new_set = mink_add(square, square)

new_set


[array([0, 0]),
 array([1, 0]),
 array([0, 1]),
 array([1, 0]),
 array([2, 0]),
 array([2, 1]),
 array([2, 1]),
 array([2, 2]),
 array([1, 2]),
 array([0, 1]),
 array([1, 2]),
 array([0, 2])]